version: '3.4'

services:
  outland:
    build:
      context: .
    image: outland
    container_name: outland
    volumes:
      - .:/app
    ports: 
      - "8080:8080"
    env_file:
      - ./settings.env
    depends_on:
      - postgres
    

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./settings.env
      